export default{
  isLoading: false,
  isLoaded: false,
  navBarKey: 0,
  dataCompleted: false,
  hasVaga: false,
  auth: {},
  tipoPermissao: '',
  pessoaFisicaInfo: {},
  pessoaJuridicaInfo: {},
  pessoaFisicaCurriculo: {},
  juridicaPatrocinadoras: [],
  itemsAreaAtuacao: [],
  upload:{
    path: ''
  },
  candidaturas: [],
  vagas: [],
  vagasComCandidaturas: [],
  vagasComConvites: [],
  counter: {},
  vagasJuridica: [],
  vagasCandidaturas: [],
  progressBar: [],
  vagasConvites: [],
  resultado: [],
  agenda: [],
  convites: [],
  juridicaUsers: [],
  isFetching: true
}