export default { 
    LOGIN: 'login',
    LOGOUT: 'logout',
    
    CREATE_PESSOA_FISICA: 'createPessoaFisica',
    CREATE_PESSOA_JURIDICA: 'createPessoaJuridica',
    CREATE_NOVO_AGENDAMENTO: 'createNovoAgendamento',
    CREATE_NOVA_VAGA: 'createNovaVaga',
    CREATE_NOVO_CONVITE: 'createNovoConvite',
    
    COMPLETE_PESSOA_FISICA: 'completePessoaFisica',
    COMPLETE_PESSOA_JURIDICA: 'completePessoaJuridica',
    
    GET_JURIDICA_USERS: 'getJuridicaUsers',
    GET_JURIDICA_PATROCINADORAS: 'getJuridicaPatrocinadoras',
    GET_PESSOA_FISICA: 'getPessoaFisica',
    GET_PESSOA_JURIDICA: 'getPessoaJuridica',
    GET_AREAS: 'getAreas',
    GET_CANDIDATURAS: 'getCandidaturas',
    GET_VAGAS_RECOMENDADAS: 'getVagasRecomendadas',
    GET_TODOS_CONVITES: 'getTodosConvites',
    GET_AGENDA: 'getAgenda',
    GET_VAGAS_JURIDICAS: "getVagasJuridicas",
    GET_PORCENTAGEM_VAGAS: 'getPorcentagemVagas',
    GET_BUSCA_VAGAS: 'getBuscaVagas', 
    GET_BUSCA_AVANCADA_VAGAS: 'getBuscaAvancadaVagas',
    GET_BUSCA_CURRICULOS: 'getBuscaCurriculos',
    GET_BUSCA_AVANCADA_CURRICULOS: 'getBuscaAvancadaCurriculos',

    UPDATE_USER_PIC: 'updateUserPic',
    UPDATE_PESSOA_FISICA: 'updatePessoaFisica',
    UPDATE_PESSOA_JURIDICA: 'updatePessoaJuridica',
    UPDATE_AGENDAMEcNTO: 'updateNovoAgendamento',
    UPDATE_VAGA: 'updateVaga',
    UPDATE_VAGA_STATUS: 'updateVagaStatus',
    UPDATE_USER_FISICA: 'updateUserFisica',
    UPDATE_USER_JURIDICA: 'updateUserJuridica',
    UPDATE_AGENDAMENTO: 'updateAgendamento',
    REQUEST_VAGA_DASH: 'requestVagaDash',
    
    REATIVAR_CONTA: 'reativarConta',

    DELETE_USER_PIC: 'deleteUserPic',
    DELETE_VAGA: 'deleteVaga',
    DESATIVAR_CONTA: 'desativaConta',
    FINALIZAR_CANDIDATURA: 'finalizarCandidatura',
    CANCELAR_CONVITE: 'cancelarConvite',
    CANCELAR_CANDIDATURA: 'cancelarCandidatura',
    CANCELAR_AGENDAMENTO: 'cancelarAgendamento',

    HANDLE_USER_STATUS: 'handleUserStatus',
    RESPOSTA_CONVITE: 'respostaConvite',
    FORGOT_PASSWORD: 'forgotPassword',
    RESET_PASSWORD: 'resetPassword',
    CONFIRM_AGENDAMENTO: 'confirmAgendamento'
} 