export default {
    SET_LOADING_SCREEN: 'setLoadingScreen',
    LOGIN: 'authSuccess', 
    LOGOUT: 'authLogout',
    SET_DATA_COMPLETED: 'dataCompleted',
    TIPO_PERMISSAO: 'tipoPermissao',
    SET_INFOS_PESSOAIS_FISICA: 'setInfosPessoaisFisica',
    SET_NEW_USER_PIC: 'setNewUserPic',
    SET_CONVITES: 'setConvites',
    SET_CANDIDATURAS: 'setCandidaturas',
    SET_VAGAS_COM_CANDIDATURAS: 'setVagasComCandidaturas',
    SET_VAGAS: 'setVagasRecomendadas',
    SET_AGENDA: 'setAgenda',
    SET_COUNTER_VAGAS_ATIVAS: 'setCounterVagasAtivas',
    SET_COUNTER_CANDIDATURAS: 'setCounterCandidaturas',
    SET_COUNTER_CONVITES: 'setCounterConvites',
    SET_COUNTER_AGENDA: 'setAgendaCounter',
    SET_PROGRESS_BAR: 'setProgressBar',
    SET_RESULTADO: 'setResultado',
    UPDATE_FISICA_USER_DATA: 'updateFisicaUserData',
    UPDATE_JURIDICA_USER_DATA: 'updateJuridicaUserData',
    PESSOA_FISICA_INFO: 'pessoaFisicaInfo',
    PESSOA_JURIDICA_INFO: 'pessoaJuridicaInfo',
    JURIDICA_USERS: 'juridicaUsers',
    PESSOA_FISICA_CURRICULO: 'pessoaFisicaCurriculo',
    DELETE_CANDIDATURA_CANCELADA: 'deleteCandidaturaCancelada'
}